---
default:
  dynaconf_merge: true
  db:
    username: "dbuser"
    password: "Secret1234"

test:
  dynaconf_merge: true
  db:
    password: "NewSecret789"

stage:
  dynaconf_merge: true
  db:
    password: "Better secret"
